import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/nav/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: "NextMatch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ToastContainer position="bottom-right" theme="colored" hideProgressBar />
          <Navbar />
          <main className="container mt-24 mx-auto">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
